spring.application.name=practice
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8081

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PAASWORD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}

spring.mail.host=${MAIL_HOST}
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL-PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true